site_name: 客户端知识图谱

copyright: 'Copyright &copy; 2020 Ivan J. Lee.'

nav:
    - 主页: index.md
    - Android基础:
      - 【四大组件】Activity: Android/activity.md
      - 【四大组件】Service: Android/service.md
    - Java基础:
      - ./Java/注解.md
    - Kotlin基础:
      - ./about.md
    - 跨平台技术:
      - ./about.md
    - CS理论基础:
      - ./about.md
    - 关于: about.md

theme:
  language: zh
  name: 'material'
  favicon: assets/book.png
  palette:
    primary: 'teal'
    accent: 'white'
  
extra_css:
  - 'css/app.css'